language: node_js
sudo: false
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
install:
  - npm install
  - npm update
  - npm install -gD codecov
script:
  - npm test
after_success:
    - bash <(curl -s https://codecov.io/bash)
